# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: oictl 
    env:
      - CGO_ENABLED=0
    dir: cmd/oictl
    binary: oictl
    goos:
      - linux
      - darwin

  - id: catalog/http
    env:
      - CGO_ENABLED=0
    dir: cmd/catalog/http
    binary: http-{{ .Env.HTTP_SERVICE_VERSION }}
    goos:
      - linux
      - darwin

  - id: catalog/slack
    env:
      - CGO_ENABLED=0
    dir: cmd/catalog/slack
    binary: slack-{{ .Env.SLACK_SERVICE_VERSION }}
    goos:
      - linux
      - darwin

  - id: catalog/github
    env:
      - CGO_ENABLED=0
    dir: cmd/catalog/github
    binary: github-{{ .Env.GITHUB_SERVICE_VERSION }}
    goos:
      - linux
      - darwin


dockers:
  - ids:
    - oictl
    image_templates:
    - openintegration/oi:latest
    - openintegration/oi:{{ .Tag }}
    dockerfile: Dockerfile
    build_flag_templates:
    - "--build-arg=SHA={{.FullCommit}}"
    
  - ids:
    - catalog/http
    image_templates:
    - openintegration/serivce-http:latest
    - openintegration/serivce-http:{{ .Env.HTTP_SERVICE_VERSION }}
    dockerfile: catalog/shared/Dockerfile
    build_flag_templates:
    - "--build-arg=SERVICE=http"

  - ids:
    - catalog/slack
    image_templates:
    - openintegration/serivce-slack:latest
    - openintegration/serivce-slack:{{ .Env.SLACK_SERVICE_VERSION }}
    dockerfile: catalog/shared/Dockerfile
    build_flag_templates:
    - "--build-arg=SERVICE=slack"

  - ids:
    - catalog/github
    image_templates:
    - openintegration/serivce-github:latest
    - openintegration/serivce-github:{{ .Env.GITHUB_SERVICE_VERSION }}
    dockerfile: catalog/shared/Dockerfile
    build_flag_templates:
    - "--build-arg=SERVICE=github"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
brews:
  - ids:
    - oictl
    tap:
      owner: open-integration
      name: homebrew-oictl
    folder: Formula
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
