name: ci

on:
  pull_request:
    branches:
      - master
jobs:
  main:
    container:
      image: openintegration/testing
      credentials:
        username: ${{ secrets.dockerhub_username }}
        password: ${{ secrets.dockerhub_password }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: make test-fmt
      - run: make spellcheck
      - run: make lint
      - run: make security-check
      - run: make test
      - uses: codecov/codecov-action@v1
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'