name: CI

on:
  pull_request:
    branches:
      - master
jobs:
  main:
    container:
      image: openintegration/testing
      # credentials:
      #   username: ${{ secrets.DOCKERHUB_USERNAME }}
      #   password: ${{ secrets.DOCKERHUB_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-staticcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
      - run: make test-all
      - uses: codecov/codecov-action@v1
      - run: make build