
name: Release Service Catalog

on:
  push:
    tags:
      - '*'
jobs:
  release:
    container:
      image: openintegration/testing
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make build-service-catalog
      - run: make release-service-catalog
        env:
          GOOGLE_SERVICE_ACCOUNT_B64: ${{ .secrets.GOOGLE_SERVICE_ACCOUNT_B64 }}
          GCS_BUCKET: ${{ .secrets.GCS_BUCKET }}
          GCS_PROJECT: ${{ .secrets.GCS_PROJECT }}
