
name: Release Service Catalog

on:
  push:
    tags:
      - '*'
jobs:
  release:
    container:
      image: openintegration/testing
      credentials:
        username: ${{ secrets.dockerhub_username }}
        password: ${{ secrets.dockerhub_password }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make release-service-catalog
